name: owamp-workflow
 
on:
  workflow_dispatch:
    inputs: 
      BUILD_VARS_JSON:
        description: 'Build var json file'
        required: true
  workflow_run:
    workflows: "Build owamp artifacts and pass runid"
    branches: 'github-workflow'
    types:
      - completed      
 
jobs:
  
  call-reusable:
    uses: cs1867/project/.github/workflows/prepare-build.yml@master
    with:
      BUILD_VARS_JSON: ${{ inputs.BUILD_VARS_JSON }}

  show-result:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: |
         echo "Build OS : ${{ needs.call-reusable.outputs.BUILD_OS }}"
         echo "Build TYPE : ${{ needs.call-reusable.outputs.BUILD_TYPE }}"
         echo "Build BRANCH : ${{ needs.call-reusable.outputs.BUILD_BRANCH }}"

  oneshot-build:
    needs: call-reusable
    uses: cs1867/project/.github/workflows/oneshot-script-build.yml@master
    secrets:
      GIT_ACTIONS: ${{ secrets.GIT_ACTIONS }}
    with:
      BUILD_OS: ${{ needs.call-reusable.outputs.BUILD_OS }}
      BUILD_TYPE: ${{ needs.call-reusable.outputs.BUILD_TYPE }}
      BUILD_BRANCH: ${{ needs.call-reusable.outputs.BUILD_BRANCH }}
      BUILD_VARS_JSON: ${{ needs.call-reusable.outputs.BUILD_VARS_JSON }}

  post-build:
    needs: 
      - call-reusable
      - oneshot-build
    uses: cs1867/project/.github/workflows/post-build.yml@master
    with:
      BUILD_OS: ${{ needs.call-reusable.outputs.BUILD_OS }}
      BUILD_TYPE: ${{ needs.call-reusable.outputs.BUILD_TYPE }}
      BUILD_BRANCH: ${{ needs.call-reusable.outputs.BUILD_BRANCH }}
      BUILD_VARS_JSON: ${{ needs.call-reusable.outputs.BUILD_VARS_JSON }}
 
          
  
 
 
    #    
    #    - name: Delete current repo from build
    #      id: modify_json
    #      run: |
    #        modified_json=$(echo "$BUILD_VARS_JSON" | jq 'del(.repos[0])')
    #        echo "Modified JSON:"
    #        echo "$modified_json" | jq .
    #        BUILD_VARS_JSON=$(echo "$modified_json" | jq -c '.')
    #        echo "BUILD_VARS_JSON=$BUILD_VARS_JSON" >> $GITHUB_ENV
    #        
    #    - name: Look up the next repo name to build
    #      id: extract_repo_name
    #      run: |
    #        echo "BUILD_VARS_JSON value is: $BUILD_VARS_JSON"
    #        NEXTREPO=$(echo  "$BUILD_VARS_JSON"  | jq -r '.repos[0].name' )
    #        echo "NEXTREPO=$NEXTREPO" >> $GITHUB_ENV  
    #        
    #    - name: Display NEXTREPO value
    #      run: echo "The value of NEXTREPO is $NEXTREPO"  

    #    - name: Add GitHub run ID to buildids
    #      id: add_run_id
    #      run: |
    #        GITHUB_RUN_ID=${{ github.run_id }}
    #        modified_json=$(echo "$BUILD_VARS_JSON"  | jq --arg run_id "$GITHUB_RUN_ID" '.buildids.${{ github.event.repository.name }} = $run_id')
    #        echo "Modified JSON with GitHub run ID:"
    #        echo "$modified_json" | jq .
    #        BUILD_VARS_JSON=$(echo "$modified_json" | jq -c '.')
    #        echo "BUILD_VARS_JSON=$BUILD_VARS_JSON" >> $GITHUB_ENV
    #        echo "BUILD_VARS_JSON=$BUILD_VARS_JSON" 
    #        
    #    - name: Capture end date and time
    #      id: end_time
    #      run: echo "end_time=$(date -u)" >> $GITHUB_ENV

    #    - name: Add end time to build_vars.json
    #      run: |
    #        modified_json=$(echo "$BUILD_VARS_JSON" | jq '.buildstats += { "${{ github.event.repository.name }}-end": "${{ env.end_time }}" }' )
    #        BUILD_VARS_JSON=$(echo "$modified_json" | jq -c '.')
    #        echo "BUILD_VARS_JSON=$BUILD_VARS_JSON" >> $GITHUB_ENV
    #        echo "BUILD_VARS_JSON=$BUILD_VARS_JSON"
            
    #    - name: Use modified BUILD_VARS_JSON with run id
    #      run: |
    #        echo "Using the modified BUILD_VARS_JSON environment variable:"
    #        echo "$BUILD_VARS_JSON" | jq .
         
     #   - name: Pass workflow  
     #     if: env.BUILD_TYPE == 'FULL'
     #     uses: actions/github-script@v6
     #     with:
     #       github-token: ${{ secrets.GIT_ACTIONS }}
     #       script: |
     #         await github.rest.actions.createWorkflowDispatch({
     #         owner: 'cs1867',
     #         repo: '${{ env.NEXTREPO}}',
     #         workflow_id: '${{ env.NEXTREPO}}-workflow.yml',
    #          ref: 'github-workflow',
    #           inputs: {
     #         BUILD_VARS_JSON: '${{ env.BUILD_VARS_JSON}}'
     #         }
     #         })
