#Workflow for GitHub Actions

name: owamp-workflow
 
on: 
  workflow_dispatch:
    inputs: 
      OS:
        description: 'OS to build on'
        required: true
      BUILD_VARS_JSON:
        description: 'Build var json file'
        required: true
  workflow_run:
    workflows: "Build owamp artifacts and pass runid"
    branches: 'github-workflow'
    types:
      - completed      
 
jobs:
       
  build-owamp:

 
    runs-on: ubuntu-latest

    steps:
        - name: Check out Repo
          uses: actions/checkout@v4
          with:
            ref: 5.2.0
        
        - name: Pretty-print BUILD_VARS_JSON
          run: |
            echo "$BUILD_VARS_JSON"
          
    #    - name: Download i2util artifacts 
    #      uses: actions/download-artifact@v4
    #      with:
    #         name: i2util-${{ github.event.inputs.OS }}
    #         repository: cs1867/i2util
    #         path: artifacts
    #         github-token: ${{ secrets.GIT_ACTIONS }}
    #         run-id: ${{ github.event.inputs.I2UTILID }}
      
          
    #    # github-actions-workflow.sh
    #    - name: run docker oneshot builder and github-actions-workflow.sh
    #      run: |
    #       curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - --run github-workflow.sh . '${{ github.event.inputs.OS }}'  
           
    #    - uses: actions/upload-artifact@v3
    #      with:
    #      #Name the artifact uniquely
    #        name: ${{ github.event.repository.name }}-${{ github.event.inputs.OS }}
    #        #Where the finished product lives after the build
    #        path: unibuild-repo
    #        #Don't keep these for long.  This is just a test.
    #        retention-days: 5

    #    - uses: actions/upload-artifact@v3
    #      with:
    #        #Name the artifact uniquely
    #        name: ${{ github.event.repository.name }}-${{ github.event.inputs.OS }}
    #        #Where the finished product lives after the build
    #        path: unibuild-repo
    #        #Don't keep these for long.  This is just a test.
    #        retention-days: 5
         
    #    - name: Pass workflow to pscheduler repo
    #      uses: actions/github-script@v6
    #      with:
    #        github-token: ${{ secrets.GIT_ACTIONS }}
    #        script: |
    #          await github.rest.actions.createWorkflowDispatch({
    #          owner: 'cs1867',
     #         repo: 'pscheduler',
     #         workflow_id: 'pscheduler-workflow.yml',
     #         ref: 'github-workflow',
     #          inputs: {
     #           OS: '${{ github.event.inputs.OS }}',
     #           MINORPACKAGEID: '${{ github.event.inputs.MINORPACKAGEID }}',
     #           I2UTILID: '${{ github.event.inputs.I2UTILID }}',
     #           OWAMPID: '${{ github.run_id }}'
     #         }
     #         })
